# Generated by Django 2.2 on 2019-04-29 14:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2019, 4, 29, 17, 57, 7, 822496))),
                ('due_on', models.DateTimeField(auto_now_add=True)),
                ('requirements', models.CharField(max_length=500)),
                ('field', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membername', models.CharField(max_length=50)),
                ('memberlocation', models.CharField(max_length=50)),
                ('memberemail', models.EmailField(max_length=254)),
                ('comps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Competition')),
            ],
        ),
    ]
