# Generated by Django 2.2 on 2019-04-29 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190429_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 4, 30, 0, 40, 17, 823418)),
        ),
    ]
